export const products = [
  {
    id: 1,
    title: "Hoodie",
    forGender: "male",
    url: "/images/male/malhoo1.jpg",
    description: "Black hoodie",
    availableSize: ["S", "M", "L", "XL"],
    price: "33.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 2,
    title: "Hoodie",
    forGender: "male",
    url: "/images/male/malhoo2.jpg",
    description: "Purple hoodie",
    availableSize: ["M", "L", "XL"],
    price: "36.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 3,
    title: "Hoodie",
    forGender: "male",
    url: "/images/male/malhoo3.jpg",
    description: "White hoodie",
    availableSize: ["M", "L"],
    price: "34.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 4,
    title: "Jacket",
    forGender: "male",
    url: "/images/male/maljak1.jpg",
    description: "Black jacket",
    availableSize: ["M", "L"],
    price: "37.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 5,
    title: "Jacket",
    forGender: "male",
    url: "/images/male/maljak2.jpg",
    description: "White silk jacket",
    availableSize: ["M", "L", "XL"],
    price: "35.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 6,
    title: "Jacket",
    forGender: "male",
    url: "/images/male/maljak3.jpg",
    description: "Brown jacket",
    availableSize: ["L", "XL"],
    price: "37.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 7,
    title: "Jean",
    forGender: "male",
    url: "/images/male/maljea1.jpg",
    description: "Light blue mens bottom",
    availableSize: ["S", "M", "L", "XL"],
    price: "31.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 8,
    title: "Jean",
    forGender: "male",
    url: "/images/male/maljea2.jpg",
    description: "Black mens denim",
    availableSize: ["M", "L", "XL"],
    price: "30.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 9,
    title: "Jean",
    forGender: "male",
    url: "/images/male/maljea3.jpg",
    description: "Dark blue mens denim",
    availableSize: ["S", "M", "L", "XL"],
    price: "30.50",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 10,
    title: "Shirt",
    forGender: "male",
    url: "/images/male/malshi1.jpg",
    description: "Checkered mens shirt",
    availableSize: ["S", "M", "L"],
    price: "34.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 11,
    title: "Shirt",
    forGender: "male",
    url: "/images/male/malshi2.jpg",
    description: "Orange brown mens shirt",
    availableSize: ["S", "M", "L", "XL"],
    price: "37.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 12,
    title: "Shirt",
    forGender: "male",
    url: "/images/male/malshi3.jpg",
    description: "Dark cyan male shirt",
    availableSize: ["S", "M", "L", "XL"],
    price: "35.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 13,
    title: "Short",
    forGender: "male",
    url: "/images/male/malsho1.jpg",
    description: "Spanish orange short",
    availableSize: ["S", "M", "L"],
    price: "25.00",
    isFreeShipping: false,
    quantity: 1,
  },
  {
    id: 14,
    title: "Short",
    forGender: "male",
    url: "/images/male/malsho2.jpg",
    description: "Red colour swimwear",
    availableSize: ["S", "M"],
    price: "22.00",
    isFreeShipping: false,
    quantity: 1,
  },
  {
    id: 15,
    title: "Short",
    forGender: "male",
    url: "/images/male/malsho3.jpg",
    description: "Dark blue short",
    availableSize: ["M", "L"],
    price: "28.00",
    isFreeShipping: false,
    quantity: 1,
  },
  {
    id: 16,
    title: "Skinny",
    forGender: "male",
    url: "/images/male/malski1.jpg",
    description: "Black skinny",
    availableSize: ["S", "M", "L"],
    price: "20.00",
    isFreeShipping: false,
    quantity: 1,
  },
  {
    id: 17,
    title: "Skinny",
    forGender: "male",
    url: "/images/male/malski2.jpg",
    description: "Green center open skinny",
    availableSize: ["M"],
    price: "23.00",
    isFreeShipping: false,
    quantity: 1,
  },
  {
    id: 18,
    title: "Skinny",
    forGender: "male",
    url: "/images/male/malski3.jpg",
    description: "White skinny",
    availableSize: ["L"],
    price: "24 .00",
    isFreeShipping: false,
    quantity: 1,
  },
  {
    id: 19,
    title: "Sneakers",
    forGender: "male",
    url: "/images/male/malsne1.jpg",
    description: "Orange branded sneakers",
    availableSize: ["S", "M", "L", "XL"],
    price: "50.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 20,
    title: "Sneakers",
    forGender: "male",
    url: "/images/male/malsne2.jpg",
    description: "White school sneakers",
    availableSize: ["XS", "S", "M", "L", "XL"],
    price: "29.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 21,
    title: "Sneakers",
    forGender: "male",
    url: "/images/male/malsne3.jpg",
    description: "Brown checkered sneakers",
    availableSize: ["XS", "S", "M", "L", "XL"],
    price: "35.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 22,
    title: "Sweater",
    forGender: "male",
    url: "/images/male/malswe1.jpg",
    description: "Dark teal mens sweater",
    availableSize: ["M", "L", "XL"],
    price: "32.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 23,
    title: "Sweater",
    forGender: "male",
    url: "/images/male/malswe2.jpg",
    description: "Greyscale mens clothing",
    availableSize: ["S", "M", "L"],
    price: "29.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 24,
    title: "Sweater",
    forGender: "male",
    url: "/images/male/malswe3.jpg",
    description: "Purple sweater",
    availableSize: ["S", "M", "L", "XL"],
    price: "30.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 25,
    title: "Tshirt",
    forGender: "male",
    url: "/images/male/maltsh1.jpg",
    description: "Black v-neck tshirt",
    availableSize: ["XS", "S", "M", "L"],
    price: "21.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 26,
    title: "Tshirt",
    forGender: "male",
    url: "/images/male/maltsh2.jpg",
    description: "Purple crew neck tshirt",
    availableSize: ["S", "M", "L"],
    price: "25.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 27,
    title: "Tshirt",
    forGender: "male",
    url: "/images/male/maltsh3.jpg",
    description: "White crew neck tshirt",
    availableSize: ["S", "M", "L", "XL"],
    price: "22.50",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 28,
    title: "Underwear",
    forGender: "male",
    url: "/images/male/malund1.jpg",
    description: "White boxer mens wear",
    availableSize: ["S", "M", "L", "XL"],
    price: "11.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 29,
    title: "Underwear",
    forGender: "male",
    url: "/images/male/malund2.jpg",
    description: "Black boxer mens wear",
    availableSize: ["S", "M", "L"],
    price: "10.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 30,
    title: "Underwear",
    forGender: "male",
    url: "/images/male/malund3.jpg",
    description: "Black v-cut mens wear",
    availableSize: ["S", "M", "L"],
    price: "10.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 31,
    title: "Bikini",
    forGender: "female",
    url: "/images/female/fembik1.jpg",
    description: "Purple bikini",
    availableSize: ["S", "M", "L"],
    price: "40.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 32,
    title: "Bikini",
    forGender: "female",
    url: "/images/female/fembik2.jpg",
    description: "Green bikini",
    availableSize: ["S", "M", "L"],
    price: "38.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 33,
    title: "Bikini",
    forGender: "female",
    url: "/images/female/fembik3.jpg",
    description: "White bikini",
    availableSize: ["S", "M", "L", "XL"],
    price: "39.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 34,
    title: "Blouse",
    forGender: "female",
    url: "/images/female/femblo1.jpg",
    description: "Light pink blouse",
    availableSize: ["XS", "S", "M", "L", "XL"],
    price: "41.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 35,
    title: "Blouse",
    forGender: "female",
    url: "/images/female/femblo2.jpg",
    description: "Black ribbon blouse",
    availableSize: ["S", "M", "L"],
    price: "38.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 36,
    title: "Blouse",
    forGender: "female",
    url: "/images/female/femblo3.jpg",
    description: "Blue dotted blouse",
    availableSize: ["XS", "S", "M", "L"],
    price: "38.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 37,
    title: "Bra",
    forGender: "female",
    url: "/images/female/fembra1.jpg",
    description: "Black sports bra",
    availableSize: ["M", "L"],
    price: "42.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 38,
    title: "Bra",
    forGender: "female",
    url: "/images/female/fembra2.jpg",
    description: "Green casual bra",
    availableSize: ["S", "M", "L"],
    price: "40.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 39,
    title: "Bra",
    forGender: "female",
    url: "/images/female/fembra3.jpg",
    description: "Blue tropical bra",
    availableSize: ["XS", "S", "M", "L"],
    price: "43.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 40,
    title: "Heels",
    forGender: "female",
    url: "/images/female/femhee1.jpg",
    description: "Green heels",
    availableSize: ["S", "M", "L"],
    price: "47.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 41,
    title: "Heels",
    forGender: "female",
    url: "/images/female/femhee2.jpg",
    description: "Pink heels",
    availableSize: ["S", "M", "L"],
    price: "48.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 42,
    title: "Heels",
    forGender: "female",
    url: "/images/female/femhee3.jpg",
    description: "Black heels",
    availableSize: ["S", "M", "L"],
    price: "50.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 43,
    title: "Jacket",
    forGender: "female",
    url: "/images/female/femjak1.jpg",
    description: "Golden womens jacket",
    availableSize: ["M", "L", "XL"],
    price: "46.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 44,
    title: "Jacket",
    forGender: "female",
    url: "/images/female/femjak2.jpg",
    description: "White jacket closed",
    availableSize: ["S", "M", "L", "XL"],
    price: "42.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 45,
    title: "Jacket",
    forGender: "female",
    url: "/images/female/femjak3.jpg",
    description: "Brown women jacket",
    availableSize: ["L", "XL"],
    price: "45.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 46,
    title: "Jeans",
    forGender: "female",
    url: "/images/female/femjea1.jpg",
    description: "White womens jeans",
    availableSize: ["XS", "S", "M", "L", "XL"],
    price: "41.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 47,
    title: "Jeans",
    forGender: "female",
    url: "/images/female/femjea2.jpg",
    description: "Light blue womens jeans",
    availableSize: ["XS", "S", "M", "L"],
    price: "41.50",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 48,
    title: "Jeans",
    forGender: "female",
    url: "/images/female/femjea3.jpg",
    description: "Dark blue womens jeans",
    availableSize: ["XS", "S", "M", "L", "XL"],
    price: "40.50",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 49,
    title: "Leggins",
    forGender: "female",
    url: "/images/female/femleg1.jpg",
    description: "Winter colored womens track pants",
    availableSize: ["XS", "S", "M", "L", "XL"],
    price: "43.00",
    isFreeShipping: false,
    quantity: 1,
  },
  {
    id: 50,
    title: "Leggins",
    forGender: "female",
    url: "/images/female/femleg2.jpg",
    description: "Cream colored womens leggings",
    availableSize: ["S", "M", "L"],
    price: "42.50",
    isFreeShipping: false,
    quantity: 1,
  },
  {
    id: 51,
    title: "Leggins",
    forGender: "female",
    url: "/images/female/femleg3.jpg",
    description: "Red colored yoga tights",
    availableSize: ["XS", "S", "M", "L", "XL"],
    price: "44.00",
    isFreeShipping: false,
    quantity: 1,
  },
  {
    id: 52,
    title: "Skirts",
    forGender: "female",
    url: "/images/female/femski1.jpg",
    description: "Long green skirt",
    availableSize: ["M"],
    price: "47.00",
    isFreeShipping: false,
    quantity: 1,
  },
  {
    id: 53,
    title: "Skirts",
    forGender: "female",
    url: "/images/female/femski2.jpg",
    description: "White womens skirt",
    availableSize: ["M", "L"],
    price: "50.00",
    isFreeShipping: false,
    quantity: 1,
  },
  {
    id: 54,
    title: "Skirts",
    forGender: "female",
    url: "/images/female/femski3.jpg",
    description: "Off white womens skirt",
    availableSize: ["S", "M", "L"],
    price: "48.00",
    isFreeShipping: false,
    quantity: 1,
  },
  {
    id: 55,
    title: "Sweater",
    forGender: "female",
    url: "/images/female/femswe1.jpg",
    description: "Christmas sweater",
    availableSize: ["XS", "S", "M", "L", "XL"],
    price: "37.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 56,
    title: "Sweater",
    forGender: "female",
    url: "/images/female/femswe2.jpg",
    description: "White gown sweater",
    availableSize: ["M", "L", "XL"],
    price: "38.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 57,
    title: "Sweater",
    forGender: "female",
    url: "/images/female/femswe3.jpg",
    description: "White sweater",
    availableSize: ["S", "M", "L"],
    price: "37.50",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 58,
    title: "Tshirt",
    forGender: "female",
    url: "/images/female/femtsh1.jpg",
    description: "White tshirt",
    availableSize: ["XS", "S", "M", "L", "XL"],
    price: "33.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 59,
    title: "Tshirt",
    forGender: "female",
    url: "/images/female/femtsh2.jpg",
    description: "Black tshirt",
    availableSize: ["XS", "S", "M", "L", "XL"],
    price: "34.00",
    isFreeShipping: true,
    quantity: 1,
  },
  {
    id: 60,
    title: "Tshirt",
    forGender: "female",
    url: "/images/female/femtsh3.jpg",
    description: "Pink tshirt",
    availableSize: ["XS", "S", "M", "L", "XL"],
    price: "36.00",
    isFreeShipping: true,
    quantity: 1,
  },
];
